# Generated by Django 4.0.6 on 2022-08-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='serial',
            field=models.CharField(default='0Z7Fmn3N', max_length=8),
        ),
    ]
