# Generated by Django 4.0.6 on 2022-07-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Valid'),
        ),
    ]
