# Generated by Django 4.0.6 on 2022-09-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_receipt_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='serial',
            field=models.CharField(default='dferwere', max_length=8),
        ),
    ]
