# Generated by Django 4.0.6 on 2022-07-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_receipt_serial_alter_student_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.student'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='serial',
            field=models.CharField(default='FkZTLG0g', max_length=8),
        ),
    ]
