# Generated by Django 4.0.6 on 2022-07-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_parent_student_parent_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='serial',
            field=models.CharField(default='ipcQaXOI', max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bus'),
        ),
    ]
