# Generated by Django 4.0.6 on 2022-07-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_receipt_serial_alter_student_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='serial',
            field=models.CharField(default='c7sr6xc6', max_length=8),
        ),
    ]
