# Generated by Django 4.0.6 on 2022-07-27 22:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_receipt_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.qrcode_location),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='serial',
            field=models.CharField(default='AXnJsBIc', max_length=8),
        ),
    ]
