# Generated by Django 4.0.6 on 2022-07-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_receipt_qr_code_alter_receipt_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='qr_code',
            field=models.ImageField(blank=True, default='null', upload_to='qrcode_location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='serial',
            field=models.CharField(default='76TaEGqe4F', max_length=8),
        ),
    ]
