# Generated by Django 4.0.6 on 2022-07-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_receipt_qr_code_alter_receipt_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='serial',
            field=models.CharField(default='r5IBGqJczq', max_length=8),
        ),
    ]
