# Generated by Django 4.0.6 on 2022-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_receipt_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='issued',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='serial',
            field=models.CharField(default='wqixpYhwxA', max_length=8),
        ),
    ]
